openapi: '3.0.3'
info:
  title: Marvel REST API
  version: '1.0'
servers:
  - url: 'http://localhost:3000/'
tags:
  - name: hero
    description: Create, read, update and delete Marvel heroes
paths:
  /heroes:
    get:
      tags:
        - hero
      summary: Returns a list of all heroes
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Hero'
        '404':
          description: No heroes found
  /hero/{id}:
    get:
      tags:
        - hero
      summary: Find hero by ID
      parameters:
        - name: id
          in: path
          description: ID of the hero
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: No hero was found with the provided ID
    delete:
      tags:
        - hero
      summary: Delete a hero
      parameters:
        - name: id
          in: path
          description: ID of the hero
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: No hero with the provided ID was found
  /hero:
    post:
      tags:
        - hero
      summary: Add a new hero
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '400':
          description: Invalid input
        '409':
          description: A hero with this ID already exists
    put:
      tags:
        - hero
      summary: Update an existing hero
      requestBody:
        description: Hero JSON
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Hero'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Hero'
        '404':
          description: No hero with the provided ID was found
components:
  schemas:
    Hero:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 2
        name:
          type: string
          example: Captain America
        alias:
          type: string
          example: Steve Rogers
        powers:
          type: array
          example: [ "Super strength", "Enhanced agility", "Vibranium shield" ]
          items:
            type: string